=== i6asic/lsieun.github.io/assets/xml/dtd/company.dtd
<!ELEMENT company (website,motto,logo?,contact,address,department*)>

<!ELEMENT website (#PCDATA)>
<!ELEMENT motto (#PCDATA)>
<!ELEMENT logo ANY>

<!ELEMENT contact (email|tel)+>
<!ELEMENT email EMPTY>
<!ATTLIST email href CDATA #REQUIRED
        preferred (true | false) "false">
<!ELEMENT tel (#PCDATA)>


<!ELEMENT address (street,region?,postal-code,locality,country)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT postal-code (#PCDATA)>
<!ELEMENT locality (#PCDATA)>
<!ELEMENT country (#PCDATA)>

<!ELEMENT department (employee*)>
<!ATTLIST department name CDATA #REQUIRED
        officer IDREF #IMPLIED>

<!ELEMENT employee ((name|(first-name,last-name?)),birthday?,salary)>
<!ATTLIST employee id ID #REQUIRED>


<!ELEMENT name (#PCDATA)>
<!ELEMENT first-name (#PCDATA)>
<!ELEMENT last-name (#PCDATA)>
<!ELEMENT birthday (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ATTLIST salary currency NMTOKEN #FIXED "Dollar">

<!ENTITY slogan "Where there is a will, there is a way. 有志者，事竟成">

=== i6asic/lsieun.github.io/assets/xml/dtd/company.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE company SYSTEM "company.dtd">
<company>
    <website>https://www.example.com</website>
    <motto>&slogan;</motto>
    <logo>Example</logo>
    <contact>
        <email href="mailto:service@example.com" preferred="true"/>
        <email href="mailto:admin@example.com"/>
        <tel>123-456-7890</tel>
    </contact>
    <address>
        <street>ABC</street>
        <postal-code>DEF</postal-code>
        <locality>GH</locality>
        <country>USA</country>
    </address>
    <department name="DEV" officer="user-001">
        <employee id="user-001">
            <first-name>Tom</first-name>
            <last-name>Cat</last-name>
            <salary>1000</salary>
        </employee>
        <employee id="user-002">
            <first-name>Jerry</first-name>
            <last-name>Mouse</last-name>
            <salary>1000</salary>
        </employee>
    </department>
    <department name="Market" officer="user-003">
        <employee id="user-003">
            <first-name>Lucy</first-name>
            <last-name>Green</last-name>
            <birthday>2020-01-01</birthday>
            <salary>1200</salary>
        </employee>
        <employee id="user-004">
            <first-name>Lily</first-name>
            <last-name>Green</last-name>
            <birthday>2020-01-01</birthday>
            <salary>1200</salary>
        </employee>
    </department>
    <department name="HR" officer="user-005">
        <employee id="user-005">
            <name>张三</name>
            <salary>1500</salary>
        </employee>
        <employee id="user-006">
            <name>李四</name>
            <salary>1500</salary>
        </employee>
    </department>
</company>
